name: Games
on:
    issues:
        types: [opened]
jobs:
    Connect4:
        runs-on: ubuntu-latest
        if: startsWith(github.event.issue.title, 'Connect4:')
        steps:
            - name: Setting up environment
              run: |
                echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
                echo "GOD=${{ secrets.GOD }}" >> $GITHUB_ENV
                echo "REPOSITORY_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

            - uses: actions/checkout@v3

            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name: Run Game
              run: |
                pip install PyGithub
                python games/connect4.py
                 
            - name: Commit and push changes
              run: |
                  git config user.name 'Automated'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git commit -am "bot: update README.md automatically" || echo "No changes to commit"
                  git push "https://x-access-token:${GOD}@github.com/${{ github.repository }}.git"
    Othello:
        runs-on: ubuntu-latest
        if: startsWith(github.event.issue.title, 'Othello:')
        steps:
            - name: Setting up environment
              run: |
                echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
                echo "GOD=${{ secrets.GOD }}" >> $GITHUB_ENV
                echo "REPOSITORY_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

            - uses: actions/checkout@v3

            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name: Run Game
              run: |
                pip install PyGithub
                python games/othello.py
                
            - name: Commit and push changes
              run: |
                  git config user.name 'Automated'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git commit -am "bot: update README.md automatically" || echo "No changes to commit"
                  git push "https://x-access-token:${GOD}@github.com/${{ github.repository }}.git"
    Chess:
        permissions:
          issues: write
          contents: write
        runs-on: ubuntu-latest
        if: startsWith(github.event.issue.title, 'Chess:')

        steps:
          - uses: actions/checkout@v3

          - name: Setting up Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.10"
              architecture: "x64"

          - name: Play chess
            env:
              ISSUE_NUMBER: ${{ github.event.issue.number }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              REPOSITORY_OWNER: ${{ github.repository_owner }}
            run: |
              pip install -r requirements.txt
              python chesss.py

          - name: Commit and push changes
            env:
              ISSUE_TITLE: ${{ github.event.issue.title }}
              ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
            run: |
              git config --global user.name "Automated"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git commit -am "${ISSUE_TITLE} by ${ISSUE_AUTHOR}"
              git push
