name: Update gist with most used programming languages
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  language-box:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Update
        run: npx github-lang-box@2
        env:
          GH_USERNAME: Coding4Hours
          GIST_ID: 47db63fd3e1cb787b6f62274e1188c8b
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
